const ADD_SEARCH_VAL = 'ADD_SEARCH';
const CLEAR_SEARCH = 'CLEAR_SEARCH';
const ADD_FORM_VALUES = 'ADD_FORM_VALUES';
const CLEAR_FORM_RESULTS = 'CLEAR_FORM_RESULTS';

export { ADD_SEARCH_VAL, CLEAR_SEARCH, ADD_FORM_VALUES, CLEAR_FORM_RESULTS };
